"""
app/models/order.py
─────────────────────────────────────────────────────────────────────────────
Purchase order model — the central entity of the DramaZone bot.

Order lifecycle / status state machine (req #22, #26, #32)
------------------------------------------------------------

  PENDING_PAYMENT  ──► WAITING_APPROVAL ──► APPROVED
                                        └──► REJECTED
  (any state)      ──► CANCELLED

Valid transitions:
  PENDING_PAYMENT   → WAITING_APPROVAL  (customer submits screenshot)
  PENDING_PAYMENT   → CANCELLED         (customer cancels)
  WAITING_APPROVAL  → APPROVED          (admin approves)
  WAITING_APPROVAL  → REJECTED          (admin rejects)
  REJECTED          → (new order)       (customer creates a fresh order)

Duplicate protection (req #32)
--------------------------------
The transition from PENDING_PAYMENT → WAITING_APPROVAL is performed
atomically via `findOneAndUpdate` with a `{status: "PENDING_PAYMENT"}`
filter.  This means a second concurrent screenshot submission will fail
the filter and be rejected gracefully.

Admin action tracking (req #5, #6, #38)
-----------------------------------------
`approvedBy` and `rejectedBy` are nested `AdminAction` objects that store
the full admin identity at the time of the action — not a reference that
could become stale if admin list changes.

Order code format (req #24)
-----------------------------
  DZ-YYYYMMDD-XXXX
  Where XXXX is 4 uppercase alphanumeric characters (random).
  Generated by the order service, not by this model.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, field_validator


class OrderStatus(str, Enum):
    """
    Valid order status values.

    Stored as strings in MongoDB for readability.
    Using str Enum means the value is both the enum member and the string
    stored in the database — no serialisation mapping needed.
    """

    PENDING_PAYMENT = "PENDING_PAYMENT"
    """Order created; customer has not yet submitted payment screenshot."""

    WAITING_APPROVAL = "WAITING_APPROVAL"
    """Screenshot submitted; awaiting admin review."""

    APPROVED = "APPROVED"
    """Admin confirmed payment; VIP content links sent to customer."""

    REJECTED = "REJECTED"
    """Admin rejected the payment; customer notified with reason."""

    CANCELLED = "CANCELLED"
    """Customer or system cancelled the order."""


class PaymentMethod(str, Enum):
    """Supported payment methods."""

    AYAPAY = "AYAPAY"
    UABPAY = "UABPAY"
    KPAY = "KPAY"
    WAVE = "WAVE"


class AdminAction(BaseModel):
    """
    Snapshot of the admin who performed an action on an order.

    Stored as a nested document — not a reference — so the audit record
    is self-contained and accurate even if admin list changes (req #5, #6).
    """

    adminTelegramId: int = Field(..., description="Admin's permanent Telegram user ID")
    adminUsername: Optional[str] = Field(
        default=None,
        description="Admin's @username at the time of action (may be None)",
    )
    adminFirstName: str = Field(..., description="Admin's first name at time of action")
    timestamp: datetime = Field(..., description="UTC datetime of the action")

    @property
    def display_name(self) -> str:
        """
        Admin display string for customer/admin messages (req #6).

        Returns '@username' if available, otherwise 'First Name'.
        """
        if self.adminUsername:
            return f"@{self.adminUsername}"
        return self.adminFirstName


class Order(BaseModel):
    """
    Purchase order as stored in MongoDB.

    The `_id` field is managed by MongoDB.  Orders are looked up by
    `orderCode` (unique indexed) or `telegramUserId`.
    """

    # ── Identification ──────────────────────────────
    orderCode: str = Field(
        ...,
        description="Human-readable unique order ID, e.g. DZ-20260909-AB12",
    )

    # ── Customer info (snapshot at order creation) ──
    telegramUserId: int = Field(
        ...,
        description="Customer's permanent Telegram user ID",
    )
    telegramUsername: Optional[str] = Field(
        default=None,
        description="Customer's @username at order creation time (may change later)",
    )
    telegramFirstName: str = Field(
        ...,
        description="Customer's first name at order creation time",
    )

    # ── Order content ────────────────────────────────
    movieIds: List[str] = Field(
        ...,
        min_length=1,
        max_length=5,
        description="List of Movie _id strings included in this order",
    )
    packageSize: int = Field(
        ...,
        description="Number of movies in the package (1, 3, or 5 only)",
    )

    @field_validator("packageSize")
    @classmethod
    def validate_package_size(cls, v: int) -> int:
        if v not in (1, 3, 5):
            raise ValueError("packageSize must be 1, 3, or 5")
        return v
    totalAmount: int = Field(
        ...,
        gt=0,
        description="Total order amount in MMK (from package tier pricing)",
    )

    # ── Payment ──────────────────────────────────────
    paymentMethod: Optional[str] = Field(
        default=None,
        description="Selected payment method: KPAY | WAVE",
    )
    screenshotFileId: Optional[str] = Field(
        default=None,
        description="Telegram file_id of the submitted payment screenshot",
    )
    screenshotSubmittedAt: Optional[datetime] = Field(
        default=None,
        description="UTC datetime when the screenshot was submitted",
    )

    # ── Status & admin actions ───────────────────────
    status: OrderStatus = Field(
        default=OrderStatus.PENDING_PAYMENT,
        description="Current order status — enforced via atomic DB transitions",
    )
    approvedBy: Optional[AdminAction] = Field(
        default=None,
        description="Admin who approved this order (req #5, #6)",
    )
    rejectedBy: Optional[AdminAction] = Field(
        default=None,
        description="Admin who rejected this order (req #5, #38)",
    )
    rejectionReason: Optional[str] = Field(
        default=None,
        max_length=500,
        description="Human-readable rejection reason shown to customer (req #28)",
    )

    # ── Admin message tracking (req #7) ─────────────
    adminMessageId: Optional[int] = Field(
        default=None,
        description=(
            "Telegram message ID of the admin notification for this order. "
            "Used to update/disable the Approve/Reject buttons after processing."
        ),
    )
    adminChatId: Optional[int] = Field(
        default=None,
        description="Chat ID of the admin channel/group where the notification was sent",
    )

    # ── Lifecycle timestamps ─────────────────────────
    createdAt: datetime = Field(
        ...,
        description="UTC datetime when the order was created",
    )
    updatedAt: datetime = Field(
        ...,
        description="UTC datetime of the most recent status change",
    )
